<?php use FilamentManager\Core\View; ?>
<div class="toolbar"><div><h1><?= View::t('help') ?></h1><p class="muted"><?= View::t('help_complete_intro') ?></p></div><nav class="help-jump"><a href="#workflow"><?= View::t('help_workflow_title') ?></a><a href="#warehouse"><?= View::t('warehouse') ?></a><a href="#jobs"><?= View::t('print_jobs') ?></a><a href="#notifications"><?= View::t('email_notifications') ?></a><a href="#sync"><?= View::t('synchronization') ?></a></nav></div>
<div class="cards help-cards">
<section id="workflow" class="card help-intro"><h2><?= View::t('help_how_it_works') ?></h2><p><?= View::t('help_intro') ?></p><p class="help-workflow"><strong><?= View::t('help_workflow') ?></strong></p></section>
<?php foreach(range(1,9) as $step): ?><section class="card help-step"><span class="help-step-number" aria-hidden="true"><?= $step ?></span><h2><?= View::t('help_step_'.$step.'_title') ?></h2><p><?= View::t('help_step_'.$step.'_text') ?></p></section><?php endforeach; ?>
<section class="card help-concepts"><h2><?= View::t('help_terms') ?></h2><dl><dt><?= View::t('material') ?></dt><dd><?= View::t('help_material_definition') ?></dd><dt><?= View::t('spool') ?></dt><dd><?= View::t('help_spool_definition') ?></dd><dt><?= View::t('storage_location') ?></dt><dd><?= View::t('help_location_definition') ?></dd><dt><?= View::t('slot') ?></dt><dd><?= View::t('help_slot_definition') ?></dd><dt><?= View::t('print_job') ?></dt><dd><?= View::t('help_print_job_definition') ?></dd></dl></section>
<section id="warehouse" class="card help-wide"><h2><?= View::t('help_warehouse_title') ?></h2><p><?= View::t('help_warehouse_text') ?></p><ul><li><?= View::t('help_warehouse_available') ?></li><li><?= View::t('help_warehouse_capacity') ?></li><li><?= View::t('help_warehouse_loaded') ?></li></ul><a class="button secondary-button action-button" href="<?= View::e($basePath) ?>/locations"><?= View::t('open_warehouse') ?></a></section>
<section id="jobs" class="card help-wide"><h2><?= View::t('help_print_jobs_title') ?></h2><p><?= View::t('help_print_jobs_text') ?></p><ol><li><?= View::t('help_job_import') ?></li><li><?= View::t('help_job_assign') ?></li><li><?= View::t('help_job_complete') ?></li><li><?= View::t('help_job_failed') ?></li></ol><div class="notice warning"><?= View::t('help_job_warning') ?></div><a class="button secondary-button action-button" href="<?= View::e($basePath) ?>/print-jobs"><?= View::t('open_print_jobs') ?></a></section>
<section class="card help-wide"><h2><?= View::t('help_prusaslicer_title') ?></h2><p><?= View::t('help_prusaslicer_text') ?></p><ol><li><?= View::t('help_prusaslicer_step_1') ?></li><li><?= View::t('help_prusaslicer_step_2') ?></li><li><?= View::t('help_prusaslicer_step_3') ?></li><li><?= View::t('help_prusaslicer_step_4') ?></li></ol><p class="muted"><?= View::t('help_bgcode_note') ?></p></section>
<section id="notifications" class="card help-wide"><h2><?= View::t('help_notifications_title') ?></h2><p><?= View::t('help_notifications_text') ?></p><ul><li><?= View::t('help_notification_once') ?></li><li><?= View::t('help_notification_users') ?></li><li><?= View::t('help_notification_cron') ?></li></ul><?php if($app->auth()->user()['role']==='admin'): ?><a class="button secondary-button action-button" href="<?= View::e($basePath) ?>/admin/settings"><?= View::t('open_settings') ?></a><?php endif; ?></section>
<section id="sync" class="card help-wide"><h2><?= View::t('help_sync_title') ?></h2><p><?= View::t('help_sync_text') ?></p><p><?= View::t('help_offline_text') ?></p></section>
<section class="card help-wide"><h2><?= View::t('help_roles_title') ?></h2><dl class="help-role-list"><dt><?= View::t('role_admin') ?></dt><dd><?= View::t('help_role_admin') ?></dd><dt><?= View::t('role_manager') ?></dt><dd><?= View::t('help_role_manager') ?></dd><dt><?= View::t('role_operator') ?></dt><dd><?= View::t('help_role_operator') ?></dd><dt><?= View::t('role_viewer') ?></dt><dd><?= View::t('help_role_viewer') ?></dd></dl></section>
<section class="card help-wide"><h2><?= View::t('help_backup_title') ?></h2><p><?= View::t('help_backup_text') ?></p><p><?= View::t('help_security_text') ?></p></section>
<section class="card help-wide"><h2><?= View::t('help_accuracy_title') ?></h2><p><?= View::t('help_accuracy_text') ?></p><p><?= View::t('help_openprinttag') ?></p></section>
<section class="card help-wide"><h2><?= View::t('help_daily_title') ?></h2><ul><li><?= View::t('help_daily_load') ?></li><li><?= View::t('help_daily_print') ?></li><li><?= View::t('help_daily_unload') ?></li><li><?= View::t('help_daily_audit') ?></li></ul></section>
<section class="card help-wide"><h2><?= View::t('help_troubleshooting_title') ?></h2><dl><dt><?= View::t('help_trouble_no_spool_title') ?></dt><dd><?= View::t('help_trouble_no_spool_text') ?></dd><dt><?= View::t('help_trouble_weight_title') ?></dt><dd><?= View::t('help_trouble_weight_text') ?></dd><dt><?= View::t('help_trouble_email_title') ?></dt><dd><?= View::t('help_trouble_email_text') ?></dd><dt><?= View::t('help_trouble_import_title') ?></dt><dd><?= View::t('help_trouble_import_text') ?></dd></dl></section>
</div>
