<?php use FilamentManager\Core\View; $count=max(1,count($slots)); ?>
<div class="toolbar"><h1><?= View::e($title) ?></h1><a href="<?= View::e($basePath) ?>/"><?= View::t('cancel') ?></a></div>
<form class="card" method="post" action="<?= View::e($basePath) ?><?= $printer ? '/printers/'.View::e($printer['id']) : '/printers' ?>"><?= View::csrf() ?><?php if($printer): ?><input type="hidden" name="version" value="<?= View::e($printer['version']) ?>"><?php endif; ?>
<div class="grid"><label><?= View::t('printer_name') ?><input name="name" required maxlength="120" value="<?= View::e($printer['name'] ?? '') ?>"></label><label><?= View::t('slots') ?><input name="slot_count" type="number" min="1" max="16" value="<?= View::e($count) ?>"></label></div>
<div class="grid"><label><?= View::t('manufacturer') ?><input name="manufacturer" maxlength="120" value="<?= View::e($printer['manufacturer'] ?? '') ?>"></label><label><?= View::t('model') ?><input name="model" maxlength="120" value="<?= View::e($printer['model'] ?? '') ?>"></label></div>
<label><?= View::t('description') ?><textarea name="description" maxlength="255"><?= View::e($printer['description'] ?? '') ?></textarea></label>
<h2><?= View::t('slots') ?></h2><p class="muted"><?= View::t('slot_count_help') ?></p>
<?php for($i=1;$i<=$count;$i++): $selected=$slots[$i-1]['loaded_spool_id']??''; ?><label><?= View::t('slot') ?> <?= $i ?><select name="slot_<?= $i ?>"><option value="">—</option><?php foreach($spools as $spool): ?><option value="<?= View::e($spool['id']) ?>" <?= $selected===$spool['id']?'selected':'' ?>><?= View::e($spool['material_type'].' · '.$spool['color_name'].' · '.number_format((float)$spool['current_net_weight_g'],0,',',' ').' g') ?></option><?php endforeach; ?></select></label><?php endfor; ?>
<button type="submit"><?= View::t('save') ?></button></form><?php if($printer): ?><details><summary><?= View::t('delete') ?></summary><form method="post" action="<?= View::e($basePath) ?>/printers/<?= View::e($printer['id']) ?>/delete"><?= View::csrf() ?><p class="notice error"><?= View::t('delete_printer_warning') ?></p><button class="danger-button" type="submit"><?= View::t('delete') ?></button></form></details><?php endif; ?>
