<?php

declare(strict_types=1);

namespace FilamentManager\Services;

use FilamentManager\Core\App; use FilamentManager\Core\HttpException;

final class SyncService
{
    private const MAP=[
        'printer'=>['table'=>'printers','fields'=>['name','manufacturer','model','description','status','sort_order']],
        'printer_slot'=>['table'=>'printer_slots','fields'=>['printer_id','slot_number','label','loaded_spool_id']],
        'manufacturer'=>['table'=>'manufacturers','fields'=>['name','website','notes']],
        'material'=>['table'=>'materials','fields'=>['manufacturer_id','material_type','commercial_name','color_name','color_hex','diameter_mm','density_g_cm3','nozzle_temp_min','nozzle_temp_max','bed_temp_min','bed_temp_max','notes']],
        'spool'=>['table'=>'spools','fields'=>['material_id','location_id','tag_uid','openprinttag_id','original_net_weight_g','current_net_weight_g','tare_weight_g','purchase_date','purchase_price','currency','batch_number','manufactured_at','expires_at','opened_at','last_dried_at','status','notes','openprinttag_data']],
        'location'=>['table'=>'locations','fields'=>['parent_id','name','code','description']],
    ];
    public function __construct(private readonly App $app){}
    public function changes(array $user,int $after,int $limit):array
    {
        $limit=max(1,min(500,$limit));$rows=$this->app->db()->fetchAll('SELECT sequence,entity_type,entity_id,operation,entity_version,changed_at FROM sync_changes WHERE workspace_id=? AND sequence>? ORDER BY sequence LIMIT '.$limit,[$user['workspace_id'],$after]);$changes=[];foreach($rows as $row){$payload=null;if($row['operation']==='upsert'&&isset(self::MAP[$row['entity_type']])){$map=self::MAP[$row['entity_type']];$payload=$this->app->db()->fetch('SELECT * FROM `'.$map['table'].'` WHERE id=? AND workspace_id=?',[$row['entity_id'],$user['workspace_id']]);}$row['data']=$payload;$changes[]=$row;}return ['changes'=>$changes,'cursor'=>$rows?(int)end($rows)['sequence']:$after,'hasMore'=>count($rows)===$limit];
    }
    public function push(array $user,array $mutations):array
    {
        if($user['role']==='viewer')throw new HttpException('Permission denied',403);if(count($mutations)>100)throw new HttpException('Maximum 100 mutations per request',422);$results=[];$conflicts=[];
        foreach($mutations as $mutation){if(!is_array($mutation))continue;$type=(string)($mutation['type']??'');$id=(string)($mutation['id']??'');$mutationId=(string)($mutation['clientMutationId']??'');$operation=(string)($mutation['operation']??'upsert');$baseVersion=(int)($mutation['baseVersion']??0);$uuid='/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i';if(!isset(self::MAP[$type])||!preg_match($uuid,$id)||!preg_match($uuid,$mutationId)||!in_array($operation,['upsert','delete'],true))throw new HttpException('Invalid mutation',422);if($user['role']==='operator'&&($operation==='delete'||!in_array($type,['spool','printer_slot'],true)))throw new HttpException('Permission denied for entity type',403);
            $prior=$this->app->db()->fetch('SELECT result_data FROM sync_mutations WHERE workspace_id=? AND device_id=? AND client_mutation_id=?',[$user['workspace_id'],$user['device_id'],$mutationId]);if($prior){$results[]=json_decode($prior['result_data'],true);continue;}
            $map=self::MAP[$type];$result=$this->app->db()->transaction(function($db)use($user,$mutation,$type,$id,$mutationId,$operation,$baseVersion,$map,&$conflicts){$existing=$db->fetch('SELECT * FROM `'.$map['table'].'` WHERE id=? AND workspace_id=? FOR UPDATE',[$id,$user['workspace_id']]);if($existing&&(int)$existing['version']!==$baseVersion){$conflicts[]=['type'=>$type,'id'=>$id,'expectedVersion'=>$baseVersion,'serverVersion'=>(int)$existing['version'],'serverData'=>$existing];return null;}if(!$existing&&$baseVersion!==0){$conflicts[]=['type'=>$type,'id'=>$id,'expectedVersion'=>$baseVersion,'serverVersion'=>null,'serverData'=>null];return null;}$version=$existing?(int)$existing['version']+1:1;
                if($operation==='delete'){if(!$existing)throw new HttpException('Cannot delete missing entity',409);$db->execute('UPDATE `'.$map['table'].'` SET deleted_at=UTC_TIMESTAMP(6),version=? WHERE id=?',[$version,$id]);}else{$data=is_array($mutation['data']??null)?$mutation['data']:[];$values=[];foreach($map['fields'] as $field)if(array_key_exists($field,$data))$values[$field]=$field==='openprinttag_data'&&is_array($data[$field])?json_encode($data[$field],JSON_THROW_ON_ERROR):$data[$field];$this->validateValues($db,$type,$values,$user['workspace_id']);if($type==='printer_slot'&&!empty($values['loaded_spool_id'])){$other=$db->fetch('SELECT * FROM printer_slots WHERE loaded_spool_id=? AND id<>? AND workspace_id=? AND deleted_at IS NULL FOR UPDATE',[$values['loaded_spool_id'],$id,$user['workspace_id']]);if($other){$db->execute('UPDATE printer_slots SET loaded_spool_id=NULL,version=version+1 WHERE id=?',[$other['id']]);$db->execute('INSERT INTO sync_changes(workspace_id,entity_type,entity_id,operation,entity_version,user_id,device_id) VALUES(?,?,?,?,?,?,?)',[$user['workspace_id'],'printer_slot',$other['id'],'upsert',(int)$other['version']+1,$user['id'],$user['device_id']]);$db->execute('INSERT INTO spool_movements(id,workspace_id,spool_id,movement_type,printer_id,printer_slot_id,source,user_id,device_id) VALUES(?,?,?,?,?,?,?,?,?)',[\FilamentManager\Core\Uuid::v4(),$user['workspace_id'],$values['loaded_spool_id'],'unloaded',$other['printer_id'],$other['id'],'mobile',$user['id'],$user['device_id']]);}}if($existing){if(!$values)throw new HttpException('Mutation has no writable fields',422);$sets=[];$params=[];foreach($values as $field=>$value){$sets[]='`'.$field.'`=?';$params[]=$value;}$sets[]='version=?';$params[]=$version;$params[]=$id;$db->execute('UPDATE `'.$map['table'].'` SET '.implode(',',$sets).' WHERE id=?',$params);}else{foreach($this->requiredFields($type) as $required)if(!array_key_exists($required,$values))throw new HttpException('Missing field '.$required,422);$columns=array_merge(['id','workspace_id'],array_keys($values));$params=array_merge([$id,$user['workspace_id']],array_values($values));$db->execute('INSERT INTO `'.$map['table'].'` (`'.implode('`,`',$columns).'`) VALUES ('.implode(',',array_fill(0,count($columns),'?')).')',$params);}}
                if($operation==='upsert'&&$type==='spool'&&array_key_exists('current_net_weight_g',$values)){$beforeWeight=$existing?(float)$existing['current_net_weight_g']:null;$afterWeight=(float)$values['current_net_weight_g'];if($beforeWeight===null||$beforeWeight!==$afterWeight)$db->execute('INSERT INTO spool_movements(id,workspace_id,spool_id,movement_type,weight_before_g,weight_after_g,weight_delta_g,source,user_id,device_id,client_mutation_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[\FilamentManager\Core\Uuid::v4(),$user['workspace_id'],$id,$existing?'weight_adjusted':'created',$beforeWeight,$afterWeight,$beforeWeight===null?null:$afterWeight-$beforeWeight,'mobile',$user['id'],$user['device_id'],$mutationId]);}
                if($operation==='upsert'&&$type==='printer_slot'&&array_key_exists('loaded_spool_id',$values)){$old=$existing['loaded_spool_id']??null;$new=$values['loaded_spool_id']?:null;$printerId=$values['printer_id']??$existing['printer_id']??null;if($old&&$old!==$new){$db->execute("UPDATE spools SET status='in_stock',version=version+1 WHERE id=? AND workspace_id=?",[$old,$user['workspace_id']]);$oldRow=$db->fetch('SELECT version FROM spools WHERE id=?',[$old]);$db->execute('INSERT INTO spool_movements(id,workspace_id,spool_id,movement_type,printer_id,printer_slot_id,source,user_id,device_id) VALUES(?,?,?,?,?,?,?,?,?)',[\FilamentManager\Core\Uuid::v4(),$user['workspace_id'],$old,'unloaded',$printerId,$id,'mobile',$user['id'],$user['device_id']]);$db->execute('INSERT INTO sync_changes(workspace_id,entity_type,entity_id,operation,entity_version,user_id,device_id) VALUES(?,?,?,?,?,?,?)',[$user['workspace_id'],'spool',$old,'upsert',(int)$oldRow['version'],$user['id'],$user['device_id']]);}if($new&&$new!==$old){$db->execute("UPDATE spools SET status='loaded',version=version+1 WHERE id=? AND workspace_id=? AND deleted_at IS NULL",[$new,$user['workspace_id']]);$newRow=$db->fetch('SELECT version FROM spools WHERE id=?',[$new]);$db->execute('INSERT INTO spool_movements(id,workspace_id,spool_id,movement_type,printer_id,printer_slot_id,source,user_id,device_id,client_mutation_id) VALUES(?,?,?,?,?,?,?,?,?,?)',[\FilamentManager\Core\Uuid::v4(),$user['workspace_id'],$new,'loaded',$printerId,$id,'mobile',$user['id'],$user['device_id'],$mutationId]);$db->execute('INSERT INTO sync_changes(workspace_id,entity_type,entity_id,operation,entity_version,user_id,device_id) VALUES(?,?,?,?,?,?,?)',[$user['workspace_id'],'spool',$new,'upsert',(int)$newRow['version'],$user['id'],$user['device_id']]);}}
                $db->execute('INSERT INTO sync_changes(workspace_id,entity_type,entity_id,operation,entity_version,user_id,device_id) VALUES(?,?,?,?,?,?,?)',[$user['workspace_id'],$type,$id,$operation,$version,$user['id'],$user['device_id']]);$result=['clientMutationId'=>$mutationId,'type'=>$type,'id'=>$id,'version'=>$version,'operation'=>$operation];$db->execute('INSERT INTO sync_mutations(workspace_id,device_id,client_mutation_id,result_data) VALUES(?,?,?,?)',[$user['workspace_id'],$user['device_id'],$mutationId,json_encode($result,JSON_THROW_ON_ERROR)]);return $result;});if($result)$results[]=$result;
        }
        $cursor=(int)($this->app->db()->fetch('SELECT COALESCE(MAX(sequence),0) cursor FROM sync_changes WHERE workspace_id=?',[$user['workspace_id']])['cursor']??0);return ['results'=>$results,'conflicts'=>$conflicts,'cursor'=>$cursor];
    }
    private function requiredFields(string $type):array{return match($type){'printer'=>['name'],'printer_slot'=>['printer_id','slot_number'],'manufacturer'=>['name'],'material'=>['material_type','color_name'],'spool'=>['material_id','original_net_weight_g','current_net_weight_g'],'location'=>['name'],default=>[]};}
    private function validateValues($db,string $type,array $values,string $workspaceId):void
    {
        if(isset($values['color_hex'])&&$values['color_hex']!==null&&!preg_match('/^#[0-9A-Fa-f]{6}$/',(string)$values['color_hex']))throw new HttpException('Invalid color value',422);
        foreach(['original_net_weight_g','current_net_weight_g','tare_weight_g'] as $field)if(isset($values[$field])&&(float)$values[$field]<0)throw new HttpException('Weight cannot be negative',422);
        if(isset($values['status'])){$allowed=$type==='printer'?['active','maintenance','downtime','fault','inactive']:['in_stock','loaded','empty','archived'];if(!in_array($values['status'],$allowed,true))throw new HttpException('Invalid status',422);}
        $references=match($type){'printer_slot'=>['printer_id'=>'printers','loaded_spool_id'=>'spools'],'material'=>['manufacturer_id'=>'manufacturers'],'spool'=>['material_id'=>'materials','location_id'=>'locations'],'location'=>['parent_id'=>'locations'],default=>[]};
        foreach($references as $field=>$table)if(isset($values[$field])&&$values[$field]!==''&&!$db->fetch('SELECT id FROM `'.$table.'` WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$values[$field],$workspaceId]))throw new HttpException('Invalid reference '.$field,422);
    }
}
