<?php

declare(strict_types=1);

namespace FilamentManager\Controllers;

use FilamentManager\Core\App;use FilamentManager\Core\Csrf;use FilamentManager\Core\HttpException;use FilamentManager\Core\Request;use FilamentManager\Core\Response;use FilamentManager\Core\Session;use FilamentManager\Core\Uuid;use FilamentManager\Core\View;use FilamentManager\Services\AuditService;use FilamentManager\Services\ChangeService;

final class LocationController
{
    public function __construct(private readonly App $app){}
    public function index(Request $r,?string $id=null):void{$u=$this->app->auth()->requireUser();$canManage=in_array($u['role'],['admin','manager'],true);if($id&&!$canManage)throw new HttpException('Permission denied',403);$editing=$id?$this->app->db()->fetch('SELECT * FROM locations WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]):null;if($id&&!$editing)throw new HttpException('Location not found',404);$locations=$this->app->db()->fetchAll('SELECT l.*,p.name parent_name,(SELECT COUNT(*) FROM spools s WHERE s.location_id=l.id AND s.deleted_at IS NULL) spool_count FROM locations l LEFT JOIN locations p ON p.id=l.parent_id WHERE l.workspace_id=? AND l.deleted_at IS NULL ORDER BY COALESCE(p.name,\'\'),l.name',[$u['workspace_id']]);View::render('locations',['title'=>View::t('storage_locations'),'locations'=>$locations,'editing'=>$editing,'canManage'=>$canManage,'basePath'=>$r->basePath()]);}
    public function save(Request $r,?string $id=null):void{Csrf::verify($r);$u=$this->app->auth()->requireRole('admin','manager');$name=trim((string)$r->input('name'));if($name===''||mb_strlen($name)>120)throw new HttpException('Invalid location',422);$parent=trim((string)$r->input('parent_id'))?:null;if($id!==null&&$parent===$id){Session::flash('error',View::t('location_parent_self'));Response::redirect($r->basePath().'/locations/'.$id.'/edit');}if($parent&&!$this->app->db()->fetch('SELECT id FROM locations WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$parent,$u['workspace_id']]))throw new HttpException('Invalid parent location',422);$before=null;if($id){$before=$this->app->db()->fetch('SELECT * FROM locations WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]);if(!$before)throw new HttpException('Location not found',404);$version=(int)$before['version']+1;$this->app->db()->execute('UPDATE locations SET parent_id=?,name=?,code=?,description=?,version=? WHERE id=?',[$parent,$name,trim((string)$r->input('code'))?:null,trim((string)$r->input('description'))?:null,$version,$id]);}else{$id=Uuid::v4();$version=1;$this->app->db()->execute('INSERT INTO locations(id,workspace_id,parent_id,name,code,description) VALUES(?,?,?,?,?,?)',[$id,$u['workspace_id'],$parent,$name,trim((string)$r->input('code'))?:null,trim((string)$r->input('description'))?:null]);}(new ChangeService($this->app))->record($u['workspace_id'],'location',$id,'upsert',$version,$u['id']);$after=$this->app->db()->fetch('SELECT * FROM locations WHERE id=?',[$id]);(new AuditService($this->app))->record($before?'location.updated':'location.created','location',$id,$before,$after);Session::flash('success',View::t('saved'));Response::redirect($r->basePath().'/locations');}
    public function delete(Request $r,string $id):void{Csrf::verify($r);$u=$this->app->auth()->requireRole('admin','manager');$loc=$this->app->db()->fetch('SELECT * FROM locations WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]);if(!$loc){Session::flash('error',View::t('location_not_found'));Response::redirect($r->basePath().'/locations');}if($this->app->db()->fetch('SELECT id FROM spools WHERE location_id=? AND deleted_at IS NULL LIMIT 1',[$id])||$this->app->db()->fetch('SELECT id FROM locations WHERE parent_id=? AND deleted_at IS NULL LIMIT 1',[$id])){Session::flash('error',View::t('location_in_use'));Response::redirect($r->basePath().'/locations');}$version=(int)$loc['version']+1;$this->app->db()->execute('UPDATE locations SET deleted_at=UTC_TIMESTAMP(6),version=? WHERE id=?',[$version,$id]);(new ChangeService($this->app))->record($u['workspace_id'],'location',$id,'delete',$version,$u['id']);(new AuditService($this->app))->record('location.deleted','location',$id,$loc,null);Session::flash('success',View::t('deleted_success'));Response::redirect($r->basePath().'/locations');}
}
