<?php

declare(strict_types=1);

namespace FilamentManager\Controllers;

use FilamentManager\Core\App; use FilamentManager\Core\Csrf; use FilamentManager\Core\HttpException; use FilamentManager\Core\Request; use FilamentManager\Core\Response; use FilamentManager\Core\Session; use FilamentManager\Core\View; use FilamentManager\Services\AuditService; use FilamentManager\Services\BackupService; use FilamentManager\Services\FileSecurityService; use FilamentManager\Services\UpdateService;

final class SettingsController
{
    public function __construct(private readonly App $app){}
    public function index(Request $request):void{$user=$this->app->auth()->requireRole('admin');$backup=new BackupService($this->app);$updates=new UpdateService($this->app);$currentVersion=$updates->currentVersion();$cachedFile=FM_ROOT.'/storage/cache/update.json';$update=is_file($cachedFile)?json_decode((string)file_get_contents($cachedFile),true):null;if(is_array($update)){$update['current']=$currentVersion;$update['available']=($update['published']??true)&&isset($update['latest'])&&version_compare((string)$update['latest'],$currentVersion,'>');}$devices=$this->app->db()->fetchAll('SELECT d.id,d.name,d.platform,d.app_version,d.last_seen_at,d.created_at,d.revoked_at,u.username,u.display_name,(SELECT COUNT(*) FROM api_refresh_tokens rt WHERE rt.device_id=d.id AND rt.revoked_at IS NULL AND rt.expires_at>UTC_TIMESTAMP(6)) active_refresh_tokens FROM devices d JOIN users u ON u.id=d.user_id WHERE d.workspace_id=? ORDER BY d.revoked_at IS NULL DESC,d.last_seen_at DESC,d.created_at DESC',[$user['workspace_id']]);$workspace=$this->app->db()->fetch('SELECT printer_sort_mode FROM workspaces WHERE id=?',[$user['workspace_id']]);View::render('settings',['title'=>View::t('settings'),'backups'=>$backup->list(),'securityIssues'=>(new FileSecurityService())->audit(),'update'=>$update,'currentVersion'=>$currentVersion,'devices'=>$devices,'printerSortMode'=>$workspace['printer_sort_mode']??'az','recentErrors'=>$this->recentErrors(),'basePath'=>$request->basePath()]);}
    public function savePrinterSort(Request $request):void{Csrf::verify($request);$user=$this->app->auth()->requireRole('admin');$mode=(string)$request->input('printer_sort_mode','az');if(!in_array($mode,['az','za','custom'],true))throw new HttpException('Invalid printer sort mode',422);$before=$this->app->db()->fetch('SELECT printer_sort_mode FROM workspaces WHERE id=?',[$user['workspace_id']]);$previous=(string)($before['printer_sort_mode']??'az');if($mode==='custom'&&$previous!=='custom'){$printers=$this->app->db()->fetchAll('SELECT id,name FROM printers WHERE workspace_id=? AND deleted_at IS NULL',[$user['workspace_id']]);usort($printers,static function(array $a,array $b)use($previous):int{$result=strnatcasecmp((string)$a['name'],(string)$b['name']);return $previous==='za'?-$result:$result;});foreach($printers as $index=>$printer)$this->app->db()->execute('UPDATE printers SET sort_order=? WHERE id=?',[$index,$printer['id']]);}$this->app->db()->execute('UPDATE workspaces SET printer_sort_mode=? WHERE id=?',[$mode,$user['workspace_id']]);(new AuditService($this->app))->record('printer.sort_mode_changed','workspace',$user['workspace_id'],$before,['printer_sort_mode'=>$mode]);Session::flash('success',View::t('printer_sort_saved'));Response::redirect($request->basePath().'/admin/settings');}
    public function revokeDevice(Request $request):void{Csrf::verify($request);$user=$this->app->auth()->requireRole('admin');$id=(string)$request->input('id');$device=$this->app->db()->transaction(function($db)use($id,$user){$record=$db->fetch('SELECT id,name,revoked_at FROM devices WHERE id=? AND workspace_id=? FOR UPDATE',[$id,$user['workspace_id']]);if(!$record)throw new HttpException('Device not found',404);$db->execute('UPDATE devices SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP(6)) WHERE id=?',[$id]);$db->execute('UPDATE api_refresh_tokens SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP(6)) WHERE device_id=?',[$id]);$db->execute('UPDATE api_access_tokens SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP(6)) WHERE device_id=?',[$id]);return $record;});(new AuditService($this->app))->record('device.revoked','device',$id,['name'=>$device['name'],'revokedAt'=>$device['revoked_at']],['name'=>$device['name'],'revoked'=>true]);Session::flash('success',View::t('device_revoked'));Response::redirect($request->basePath().'/admin/settings');}
    public function deleteDevice(Request $request):void{Csrf::verify($request);$user=$this->app->auth()->requireRole('admin');$id=(string)$request->input('id');$device=$this->app->db()->transaction(function($db)use($id,$user){$record=$db->fetch('SELECT id,name,revoked_at FROM devices WHERE id=? AND workspace_id=? FOR UPDATE',[$id,$user['workspace_id']]);if(!$record)throw new HttpException('Device not found',404);if(!$record['revoked_at'])throw new HttpException('Revoke the device before deleting it',409);$db->execute('DELETE FROM api_access_tokens WHERE device_id=?',[$id]);$db->execute('DELETE FROM api_refresh_tokens WHERE device_id=?',[$id]);$db->execute('DELETE FROM devices WHERE id=?',[$id]);return $record;});(new AuditService($this->app))->record('device.deleted','device',$id,['name'=>$device['name'],'revokedAt'=>$device['revoked_at']],null);Session::flash('success',View::t('device_deleted'));Response::redirect($request->basePath().'/admin/settings');}
    public function deleteRevokedDevices(Request $request):void{Csrf::verify($request);$user=$this->app->auth()->requireRole('admin');$count=$this->app->db()->transaction(function($db)use($user){$row=$db->fetch('SELECT COUNT(*) total FROM devices WHERE workspace_id=? AND revoked_at IS NOT NULL',[$user['workspace_id']]);$db->execute('DELETE FROM api_access_tokens WHERE device_id IN (SELECT id FROM devices WHERE workspace_id=? AND revoked_at IS NOT NULL)',[$user['workspace_id']]);$db->execute('DELETE FROM api_refresh_tokens WHERE device_id IN (SELECT id FROM devices WHERE workspace_id=? AND revoked_at IS NOT NULL)',[$user['workspace_id']]);$db->execute('DELETE FROM devices WHERE workspace_id=? AND revoked_at IS NOT NULL',[$user['workspace_id']]);return (int)($row['total']??0);});(new AuditService($this->app))->record('devices.deleted','device',null,['revokedCount'=>$count],null);Session::flash('success',View::t('revoked_devices_deleted',['count'=>$count]));Response::redirect($request->basePath().'/admin/settings');}
    public function backup(Request $request):void{Csrf::verify($request);$this->app->auth()->requireRole('admin');$path=(new BackupService($this->app))->create();(new AuditService($this->app))->record('backup.created');header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.basename($path).'"');header('Content-Length: '.filesize($path));header('Cache-Control: no-store');readfile($path);exit;}
    public function deleteBackup(Request $request):void{Csrf::verify($request);$this->app->auth()->requireRole('admin');$name=(string)$request->input('name');try{(new BackupService($this->app))->delete($name);(new AuditService($this->app))->record('backup.deleted','backup',null,['name'=>$name],null);Session::flash('success',View::t('backup_deleted'));}catch(\Throwable $e){Session::flash('error',View::t('backup_delete_failed',['message'=>$e->getMessage()]));}Response::redirect($request->basePath().'/admin/settings');}
    public function restore(Request $request):void{Csrf::verify($request);$u=$this->app->auth()->requireRole('admin');$record=$this->app->db()->fetch('SELECT password_hash FROM users WHERE id=?',[$u['id']]);if(!$record||!password_verify((string)$request->input('password'),$record['password_hash']))throw new HttpException('Administrator password is incorrect',403);$file=$request->file('backup');if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||($file['size']??0)>100*1024*1024)throw new HttpException('Invalid backup upload',422);(new BackupService($this->app))->create('pre-restore');(new BackupService($this->app))->restore($file['tmp_name']);if($this->app->db()->fetch('SELECT id FROM users WHERE id=?',[$u['id']]))(new AuditService($this->app))->record('backup.restored');$this->app->auth()->logout();Response::redirect($request->basePath().'/login');}
    public function checkUpdate(Request $request):void{Csrf::verify($request);$this->app->auth()->requireRole('admin');try{$result=(new UpdateService($this->app))->check(true);Session::flash('success',($result['published']??true)?($result['available']?View::t('new_version_available',['version'=>$result['latest']]):View::t('up_to_date')):View::t('no_releases'));}catch(\Throwable $e){Session::flash('error',View::t('update_check_failed',['message'=>$e->getMessage()]));}Response::redirect($request->basePath().'/admin/settings');}
    public function installUpdate(Request $request):void{Csrf::verify($request);$u=$this->app->auth()->requireRole('admin');$record=$this->app->db()->fetch('SELECT password_hash FROM users WHERE id=?',[$u['id']]);if(!$record||!password_verify((string)$request->input('password'),$record['password_hash']))throw new HttpException('Administrator password is incorrect',403);$result=(new UpdateService($this->app))->install((string)$request->input('version'));(new AuditService($this->app))->record('server.updated',null,null,null,$result);Session::flash('success',View::t('updated_to_version',['version'=>$result['version']]));Response::redirect($request->basePath().'/admin/settings');}
    private function recentErrors():array{$path=FM_ROOT.'/storage/logs/app.log';if(!is_file($path))return [];$size=(int)filesize($path);$offset=max(0,$size-65536);$content=(string)file_get_contents($path,false,null,$offset);if($offset>0){$newline=strpos($content,"\n");$content=$newline===false?'':substr($content,$newline+1);}$lines=array_values(array_filter(array_map('trim',preg_split('/\R/',$content)?:[]),static fn(string $line):bool=>$line!==''));return array_slice($lines,-20);}
}
