<?php

declare(strict_types=1);

namespace FilamentManager\Controllers;

use FilamentManager\Core\App; use FilamentManager\Core\Csrf; use FilamentManager\Core\HttpException; use FilamentManager\Core\Request; use FilamentManager\Core\Response; use FilamentManager\Core\Session; use FilamentManager\Core\Uuid; use FilamentManager\Core\View;
use FilamentManager\Services\AuditService; use FilamentManager\Services\ChangeService;

final class SpoolController
{
    public function __construct(private readonly App $app){}
    public function index(Request $request):void{$u=$this->app->auth()->requireUser();$rows=$this->app->db()->fetchAll('SELECT s.*,m.material_type,m.color_name,m.color_hex,m.commercial_name,mf.name manufacturer_name,l.name location_name FROM spools s JOIN materials m ON m.id=s.material_id LEFT JOIN manufacturers mf ON mf.id=m.manufacturer_id LEFT JOIN locations l ON l.id=s.location_id WHERE s.workspace_id=? AND s.deleted_at IS NULL ORDER BY FIELD(s.status,\'loaded\',\'in_stock\',\'empty\',\'archived\'),m.material_type,m.color_name',[$u['workspace_id']]);View::render('spools',['title'=>View::t('spools'),'spools'=>$rows,'basePath'=>$request->basePath()]);}
    public function form(Request $request,?string $id=null):void{$u=$this->app->auth()->requireRole('admin','manager','operator');$spool=$id?$this->app->db()->fetch('SELECT * FROM spools WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]):null;if($id&&!$spool)throw new HttpException('Spool not found',404);$materials=$this->app->db()->fetchAll('SELECT id,material_type,color_name,commercial_name FROM materials WHERE workspace_id=? AND deleted_at IS NULL ORDER BY material_type,color_name',[$u['workspace_id']]);$locations=$this->app->db()->fetchAll('SELECT id,name,code FROM locations WHERE workspace_id=? AND deleted_at IS NULL ORDER BY name',[$u['workspace_id']]);View::render('spool_form',['title'=>$id?View::t('edit'):View::t('spools'),'spool'=>$spool,'materials'=>$materials,'locations'=>$locations,'basePath'=>$request->basePath()]);}
    public function save(Request $request,?string $id=null):void{
        Csrf::verify($request);$u=$this->app->auth()->requireRole('admin','manager','operator');$materialId=(string)$request->input('material_id');$material=$this->app->db()->fetch('SELECT id FROM materials WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$materialId,$u['workspace_id']]);if(!$material)throw new HttpException('Invalid material',422);
        $weight=max(0,(float)$request->input('current_net_weight_g'));$original=max($weight,(float)$request->input('original_net_weight_g',$weight));$tag=trim((string)$request->input('tag_uid'))?:null;$locationId=trim((string)$request->input('location_id'))?:null;if($locationId&&!$this->app->db()->fetch('SELECT id FROM locations WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$locationId,$u['workspace_id']]))throw new HttpException('Invalid storage location',422);$before=null;
        $this->app->db()->transaction(function($db)use(&$id,&$before,$u,$materialId,$locationId,$weight,$original,$tag,$request){if($id){$before=$db->fetch('SELECT * FROM spools WHERE id=? AND workspace_id=? AND deleted_at IS NULL FOR UPDATE',[$id,$u['workspace_id']]);if(!$before)throw new HttpException('Spool not found',404);if((int)$request->input('version',0)!==(int)$before['version'])throw new HttpException('Spool was changed by another user. Reload the form.',409);$effectiveLocation=$before['status']==='loaded'?$before['location_id']:$locationId;$version=(int)$before['version']+1;$db->execute('UPDATE spools SET material_id=?,location_id=?,current_net_weight_g=?,original_net_weight_g=?,tare_weight_g=?,tag_uid=?,openprinttag_id=?,purchase_date=?,batch_number=?,notes=?,version=? WHERE id=?',[$materialId,$effectiveLocation,$weight,$original,$request->input('tare_weight_g')!==''?(float)$request->input('tare_weight_g'):null,$tag,trim((string)$request->input('openprinttag_id'))?:null,$request->input('purchase_date')?:null,trim((string)$request->input('batch_number'))?:null,trim((string)$request->input('notes'))?:null,$version,$id]);if($effectiveLocation!==$before['location_id'])$db->execute('INSERT INTO spool_movements(id,workspace_id,spool_id,movement_type,from_location_id,to_location_id,source,user_id) VALUES(?,?,?,?,?,?,?,?)',[Uuid::v4(),$u['workspace_id'],$id,'transferred',$before['location_id'],$effectiveLocation,'web',$u['id']]);}else{$id=Uuid::v4();$version=1;$db->execute('INSERT INTO spools(id,workspace_id,material_id,location_id,tag_uid,openprinttag_id,original_net_weight_g,current_net_weight_g,tare_weight_g,purchase_date,batch_number,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[$id,$u['workspace_id'],$materialId,$locationId,$tag,trim((string)$request->input('openprinttag_id'))?:null,$original,$weight,$request->input('tare_weight_g')!==''?(float)$request->input('tare_weight_g'):null,$request->input('purchase_date')?:null,trim((string)$request->input('batch_number'))?:null,trim((string)$request->input('notes'))?:null]);}
            if(!$before||(float)$before['current_net_weight_g']!==$weight)$db->execute('INSERT INTO spool_movements(id,workspace_id,spool_id,movement_type,from_location_id,to_location_id,weight_before_g,weight_after_g,weight_delta_g,source,user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[Uuid::v4(),$u['workspace_id'],$id,$before?'weight_adjusted':'created',null,$before?null:$locationId,$before?$before['current_net_weight_g']:null,$weight,$before?$weight-(float)$before['current_net_weight_g']:null,'web',$u['id']]);(new ChangeService($this->app))->record($u['workspace_id'],'spool',$id,'upsert',$version,$u['id']);});
        $after=$this->app->db()->fetch('SELECT * FROM spools WHERE id=?',[$id]);(new AuditService($this->app))->record($before?'spool.updated':'spool.created','spool',$id,$before,$after);Session::flash('success',View::t('saved'));Response::redirect($request->basePath().'/spools');
    }
    public function delete(Request $request,string $id):void{Csrf::verify($request);$u=$this->app->auth()->requireRole('admin','manager');$s=$this->app->db()->fetch('SELECT * FROM spools WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]);if(!$s)throw new HttpException('Spool not found',404);if($this->app->db()->fetch('SELECT id FROM printer_slots WHERE loaded_spool_id=? AND deleted_at IS NULL',[$id])){Session::flash('error',View::t('spool_loaded_delete'));Response::redirect($request->basePath().'/spools');}$version=(int)$s['version']+1;$this->app->db()->execute("UPDATE spools SET deleted_at=UTC_TIMESTAMP(6),status='archived',version=? WHERE id=?",[$version,$id]);(new ChangeService($this->app))->record($u['workspace_id'],'spool',$id,'delete',$version,$u['id']);(new AuditService($this->app))->record('spool.deleted','spool',$id,$s,null);Session::flash('success',View::t('deleted_success'));Response::redirect($request->basePath().'/spools');}
}
