<?php

declare(strict_types=1);

namespace FilamentManager\Controllers;

use FilamentManager\Core\App; use FilamentManager\Core\Csrf; use FilamentManager\Core\HttpException; use FilamentManager\Core\Request; use FilamentManager\Core\Response; use FilamentManager\Core\Session; use FilamentManager\Core\Uuid; use FilamentManager\Core\View; use FilamentManager\Services\AuditService;

final class UserController
{
    public function __construct(private readonly App $app){}
    public function index(Request $request,?string $id=null):void{$u=$this->app->auth()->requireRole('admin');$editing=$id?$this->app->db()->fetch('SELECT id,username,email,display_name,role,locale,is_active FROM users WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]):null;if($id&&!$editing)throw new HttpException('User not found',404);$users=$this->app->db()->fetchAll('SELECT id,username,email,display_name,role,locale,is_active,last_login_at,created_at FROM users WHERE workspace_id=? AND deleted_at IS NULL ORDER BY username',[$u['workspace_id']]);View::render('users',['title'=>View::t('users'),'users'=>$users,'editing'=>$editing,'basePath'=>$request->basePath()]);}
    public function save(Request $request,?string $id=null):void{Csrf::verify($request);$u=$this->app->auth()->requireRole('admin');$username=trim((string)$request->input('username'));$email=trim((string)$request->input('email'))?:null;$password=(string)$request->input('password');$role=(string)$request->input('role');if(!preg_match('/^[A-Za-z0-9_.-]{3,80}$/',$username)||(!$id&&strlen($password)<12)||($password!==''&&strlen($password)<12)||!in_array($role,['admin','manager','operator','viewer'],true))throw new HttpException('Invalid user data',422);if($this->app->db()->fetch('SELECT id FROM users WHERE workspace_id=? AND id<>? AND (username=? OR (email IS NOT NULL AND email=?)) LIMIT 1',[$u['workspace_id'],$id??'',$username,$email])){Session::flash('error',View::t('user_exists'));Response::redirect($request->basePath().($id?'/admin/users/'.$id.'/edit':'/admin/users'));}$locale=in_array($request->input('locale'),['cs','en'],true)?$request->input('locale'):'cs';$displayName=trim((string)$request->input('display_name'))?:$username;$before=null;if($id){$before=$this->app->db()->fetch('SELECT * FROM users WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]);if(!$before)throw new HttpException('User not found',404);if($id===$u['id'])$role='admin';$params=[$username,$email,$displayName,$role,$locale];$sql='UPDATE users SET username=?,email=?,display_name=?,role=?,locale=?';if($password!==''){$sql.=',password_hash=?';$params[]=password_hash($password,PASSWORD_DEFAULT);}$sql.=' WHERE id=?';$params[]=$id;$this->app->db()->execute($sql,$params);}else{$id=Uuid::v4();$this->app->db()->execute('INSERT INTO users(id,workspace_id,username,email,display_name,password_hash,role,locale) VALUES(?,?,?,?,?,?,?,?)',[$id,$u['workspace_id'],$username,$email,$displayName,password_hash($password,PASSWORD_DEFAULT),$role,$locale]);}$after=$this->app->db()->fetch('SELECT id,username,email,display_name,role,locale,is_active FROM users WHERE id=?',[$id]);(new AuditService($this->app))->record($before?'user.updated':'user.created','user',$id,$before,$after);Session::flash('success',View::t('saved'));Response::redirect($request->basePath().'/admin/users');}
    public function toggle(Request $request,string $id):void{Csrf::verify($request);$u=$this->app->auth()->requireRole('admin');if($id===$u['id']){Session::flash('error',View::t('cannot_disable_self'));Response::redirect($request->basePath().'/admin/users');}$target=$this->app->db()->fetch('SELECT id,username,is_active FROM users WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]);if(!$target){Session::flash('error',View::t('user_not_found'));Response::redirect($request->basePath().'/admin/users');}$active=(int)!((bool)$target['is_active']);$this->app->db()->execute('UPDATE users SET is_active=? WHERE id=?',[$active,$id]);if(!$active)$this->app->db()->execute('UPDATE devices SET revoked_at=UTC_TIMESTAMP(6) WHERE user_id=? AND revoked_at IS NULL',[$id]);(new AuditService($this->app))->record('user.status_changed','user',$id,['is_active'=>$target['is_active']],['is_active'=>$active]);Session::flash('success',View::t('saved'));Response::redirect($request->basePath().'/admin/users');}
    public function delete(Request $request,string $id):void{Csrf::verify($request);$u=$this->app->auth()->requireRole('admin');if($id===$u['id']){Session::flash('error',View::t('cannot_delete_self'));Response::redirect($request->basePath().'/admin/users');}$target=$this->app->db()->fetch('SELECT id,username,email,display_name,role,is_active FROM users WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[$id,$u['workspace_id']]);if(!$target){Session::flash('error',View::t('user_not_found'));Response::redirect($request->basePath().'/admin/users');}$passwordHash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);$this->app->db()->transaction(function($db)use($id,$passwordHash):void{$db->execute('UPDATE devices SET revoked_at=UTC_TIMESTAMP(6) WHERE user_id=? AND revoked_at IS NULL',[$id]);$db->execute("UPDATE users SET username=CONCAT('deleted-',id),email=NULL,display_name='Deleted user',password_hash=?,role='viewer',is_active=0,deleted_at=UTC_TIMESTAMP(6) WHERE id=?",[$passwordHash,$id]);});(new AuditService($this->app))->record('user.deleted','user',$id,$target,null);Session::flash('success',View::t('deleted_success'));Response::redirect($request->basePath().'/admin/users');}
}
